name: animetint
description: "Bring cinematic \"Reading Mode\" vibes from tablets to Android — warm tints & grain for anime/manga"
publish_to: 'none'
version: 0.2.0 

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_overlay_window: ^0.5.0
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/kanji.png"

flutter:
  uses-material-design: true

  assets:
    - assets/